---
# role: ansible-role-samba-dc
# file: molecule/resources/playbooks/converge.yml

- name: Converge
  hosts: all
  become: true
  gather_facts: true
  serial: 1  # provision one instance at a time, so dc1 is ready for dc2 to join
  roles:
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
