---
# role: ansible-role-dc
# file: molecule/default/molecule.yml

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: archdc
    box: "archlinux/archlinux"
    cpus: 2
    memory: 2048
  - name: debian10dc
    box: "debian/buster64"
    cpus: 2
    memory: 2048
  - name: debian11dc
    box: "debian/bullseye64"
    cpus: 2
    memory: 2048
  - name: fedoradc
    box: "fedora/33-cloud-base"
    cpus: 2
    memory: 2048
  - name: ubuntudc
    box: "ubuntu/focal64"
    cpus: 2
    memory: 2048
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        hosts_ip_static: true
        hosts_domain: 'samdom.localdomain'
        samba_dc_role_enabled: true
        samba_dc_domain_provision: true
        samba_dc_dns_domain: 'samdom.localdomain'
        samba_dc_site: 'MySite'
        samba_dc_admin_password: "Chang3MeN0w!"
        samba_dc_no_log: false
        samba_dc_smb_conf:
          global:
            - "template shell = /bin/bash"
            - "template homedir = /home/%D/%U"
            - "log level = 1 auth_json_audit:3@/var/log/samba/samba_audit.log"
            - "full_audit:failure = none"
            - "full_audit:success = pwrite write rename"
            - "full_audit:prefix = IP=%I|USER=%u|MACHINE=%m|VOLUME=%S"
            - "full_audit:facility = local7"
            - "full_audit:priority = NOTICE"
          netlogon:
            - "vfs objects = dfs_samba4, acl_xattr, full_audit"
          sysvol:
            - "vfs objects = dfs_samba4, acl_xattr, full_audit"
verifier:
  name: ansible
