---
# role: ansible-role-samba-dc
# file: molecule/dev/prepare.yml

- name: Prepare
  hosts: all
  become: true
  gather_facts: true
  vars:
    pip_packages:
      - ansible
      - cryptography
  tasks:
    - name: "Update apk cache"
      community.general.apk:
        update_cache: true
      when: ansible_pkg_mgr == "apk"

    - name: "Update apt cache"
      ansible.builtin.apt:
        update_cache: true
      when: ansible_pkg_mgr == "apt"

    - name: "Update dnf cache"
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_pkg_mgr == "dnf"

    - name: "Update pacman cache"
      community.general.pacman:
        update_cache: true
      when: ansible_pkg_mgr == "pacman"

    - name: "Update zypper cache"
      community.general.zypper:
        name: sudo
        update_cache: true
      when: ansible_pkg_mgr == "zypper"

    - name: "Install Debian development"
      when: ansible_pkg_mgr == "apt"
      block:
        - name: "Upgrade all"
          ansible.builtin.apt:
            upgrade: full
        - name: "Install pip"
          ansible.builtin.apt:
            name: python3-pip
        - name: "Pip ansible"
          ansible.builtin.pip:
            name: "{{ item }}"
          loop: "{{ pip_packages }}"

    - name: "Install Fedora development"
      when: ansible_pkg_mgr == "dnf"
      block:
        - name: "Install python-pip"
          ansible.builtin.dnf:
            name: python3-pip
        - name: "Install pip packages"
          ansible.builtin.pip:
            name: "{{ item }}"
          loop: "{{ pip_packages }}"
