---
# role: ansible-role-samba-dc
# file: molecule/resources/playbooks/converge.yml

- name: Converge
  hosts: all
  become: true
  roles:
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
